### ISSUE TITLE
Data Modeling in Javascript

### ISSUE THREAD

**Issue by hxoht** [hxoht/blog#12]
![image](https://cloud.githubusercontent.com/assets/136109/20865895/3bb07ace-ba1e-11e6-9294-75b98219b660.png)
Working on [Voltra Co.](https://voltra.co.), I’ve needed to validate a lot of data. I’ve tried some pretty clever solutions for validating and describing data. But after working daily with these libraries, I’ve found that the javascript just gets in the way. Too much syntax, too much boiler plate, etc. 50+ models with 30+ entities can become a nightmare to read and maintain.

Anyway, after much GTD I took a break to put together [DML](http://voltraco.github.io/dml/). DML is a simple language with the goal of making your data models readable and maintainable. The javascript implementation is only a few hundred lines. The documentation is a work in progress at the moment but the syntax looks like this…

```js
//
// An example data model
//

Date created
Number id

String name
  require true "a name is required" // this is a comment
  gt 2 "Must be greater than 2 characters"
  lte 256 "Must be less than or equal to 256 characters"

String bio
  lte 140 "A bio must fit into a tweet"

Boolean accountType
```

Visit the project on [Github](https://github.com/voltraco/dml).

**Comment by 0x00A** [comment]
Fucking typo
