### ISSUE TITLE
Github is a CMS

### ISSUE THREAD

**Issue by hxoht** [hxoht/blog#8]
Github is basically a big content management system. So, here is an attempt to leverage it as a writing and publishing platform! Issues allow any number of authorized users to publish to the same page, hello painless collaborative blogging!

[This project](https://github.com/0x00A/blog), the blog you are reading, was co-designed and co-developed by @aprileelcich and myself. If you like it, it's MIT licensed, so fork it if you want to! There are only a few things you need to do in order to get it working for yourself...
- Change the [`CNAME`](https://github.com/0x00A/blog/blob/gh-pages/CNAME) file to include the correct domain (and obviously your DNS settings to add a CNAME record).
- Change the [`config.json`](https://github.com/0x00A/blog/blob/gh-pages/config.json) file to reflect the correct username and repository. Also make sure you add yourself to the authors array!
- Edit the static HTML, some of this is specific to me and you will want to change that.

Happy writing and if you have any questions feel free to ask them on [twitter](https://twitter.com/0x00a) or here in the comments section. Ciao. &primes;

**Comment by aprileelcich** [comment]
This sounds great!

**Comment by roccomuso** [comment]
Cool!

**Comment by dominictarr** [comment]
this is pretty cheeky :wink:
